# Generated by Django 4.2.6 on 2023-10-29 03:08

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="Nombre")),
                ("last_name", models.CharField(blank=True, default="", max_length=255, verbose_name="Apellido")),
                ("cedula", models.PositiveIntegerField(db_index=True, default=0, verbose_name="Cédula")),
                ("picture", models.ImageField(upload_to="pictures", verbose_name="Foto")),
                ("date_entry_job", models.DateField(default=None, null=True, verbose_name="Fecha de ingreso")),
            ],
            options={
                "verbose_name": "Trabajador",
                "verbose_name_plural": "Trabajadores",
                "ordering": ["date_entry_job"],
            },
        ),
    ]
