# Generated by Django 4.2.6 on 2023-10-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_employee_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeposition",
            options={"verbose_name": "Cargo", "verbose_name_plural": "Cargos"},
        ),
        migrations.AlterField(
            model_name="employeeposition",
            name="position",
            field=models.CharField(max_length=255, verbose_name="Cago"),
        ),
    ]
