# Generated by Django 4.2.6 on 2023-10-31 16:15

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0004_alter_employeeposition_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[("actived", "Activo"), ("suspended", "Suspendido"), ("rejected", "Expulsado")],
                default="actived",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
    ]
