# Generated by Django 4.2.6 on 2023-11-03 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_department"),
        ("employees", "0005_employee_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="employers",
                to="settings.department",
            ),
        ),
    ]
