# Generated by Django 4.2.6 on 2023-11-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0006_employee_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="date_entry_job",
            field=models.DateField(
                default=None, help_text="Formato: AAAA-MM-DD", null=True, verbose_name="Fecha de ingreso"
            ),
        ),
    ]
