# Generated by Django 4.2.6 on 2023-12-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0007_alter_employee_date_entry_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="birthday_at",
            field=models.DateField(
                default=None, help_text="Formato: AAAA-MM-DD", null=True, verbose_name="Fecha de cumpleaños"
            ),
        ),
        migrations.AlterField(
            model_name="employeeposition",
            name="position",
            field=models.CharField(max_length=255, verbose_name="Cargo"),
        ),
    ]
