# Generated by Django 4.2.6 on 2024-01-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_department"),
        ("employees", "0008_employee_birthday_at_alter_employeeposition_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="employers",
                to="settings.department",
                verbose_name="Departamento",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="employees.employeeposition",
                verbose_name="Cargo",
            ),
        ),
    ]
