# Generated by Django 4.2.6 on 2024-01-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0009_alter_employee_department_alter_employee_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="birthday_at",
            field=models.DateField(
                default=None, help_text="Formato: AAAA-MM-DD", null=True, verbose_name="Fecha de nacimiento"
            ),
        ),
    ]
