# Generated by Django 4.2.6 on 2024-01-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0010_alter_employee_birthday_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="deleted_at",
            field=models.DateTimeField(default=None, null=True, verbose_name="Eliminado"),
        ),
    ]
