# Generated by Django 4.2.6 on 2024-04-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0011_employee_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
    ]
