# Generated by Django 4.2.6 on 2024-09-07 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0014_transfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="transfers_made",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
    ]
