# Generated by Django 4.2.6 on 2024-12-05 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0010_workcenter_allow_clocking_from_another_workcenter"),
        ("employees", "0015_alter_transfer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employers",
                to="settings.department",
                verbose_name="Departamento",
            ),
        ),
    ]
