# Generated by Django 4.2.6 on 2025-04-08 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0014_alter_carnetmodels_options_and_more"),
        ("employees", "0016_alter_employee_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to="employees.employee",
                verbose_name="Empleado transferido",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="from_department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_origin",
                to="settings.department",
                verbose_name="Departamento de origen",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="to_department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_destination",
                to="settings.department",
                verbose_name="Departamento destino",
            ),
        ),
    ]
