# Generated by Django 4.2.6 on 2025-05-15 21:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0018_employee_is_actived"),
        ("settings", "0014_alter_carnetmodels_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("names", models.CharField(max_length=150, verbose_name="Nombres")),
                ("lastnames", models.CharField(max_length=150, verbose_name="Apellidos")),
                ("identity", models.PositiveIntegerField(db_index=True, unique=True, verbose_name="Cédula")),
                ("is_disabled", models.BooleanField(default=False, verbose_name="Personal activo")),
                (
                    "identity_pic",
                    models.ImageField(upload_to="peladoydescabezado/", verbose_name="Foto de la cédula o pasaporte"),
                ),
                ("phone", models.CharField(blank=True, default="", verbose_name="Teléfono")),
                (
                    "department",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="settings.department",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.employeeposition",
                        verbose_name="Cargo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
