# Generated by Django 4.2.6 on 2025-05-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Trabajador", "verbose_name_plural": "Personal"},
        ),
        migrations.AddField(
            model_name="person",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="Dirección"),
        ),
    ]
