# Generated by Django 4.2.6 on 2025-05-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0002_alter_person_options_person_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="personal_pic",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="peladoydescabezado/photos/",
                verbose_name="Foto de la cédula o pasaporte",
            ),
        ),
    ]
