# Generated by Django 4.2.6 on 2025-05-17 01:28

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0003_person_personal_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("description", models.CharField(max_length=50, verbose_name="Descripción de la mesa")),
                ("max_workers", models.PositiveIntegerField(default=1, verbose_name="Número máximo de trabajadores")),
                (
                    "category",
                    models.SmallIntegerField(
                        choices=[(0, "PPV"), (1, "PUD"), (2, "PYD"), (3, "Descabezado")],
                        verbose_name="Categoría de la mesa",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Mesa activa")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="person",
            name="daily_basket",
            field=models.PositiveIntegerField(default=1, verbose_name="Número diario de canastas"),
        ),
        migrations.AlterField(
            model_name="person",
            name="personal_pic",
            field=models.ImageField(
                default=None, null=True, upload_to="peladoydescabezado/photos/", verbose_name="Foto"
            ),
        ),
    ]
