# Generated by Django 4.2.6 on 2025-05-19 23:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0004_table_person_daily_basket_alter_person_personal_pic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={"verbose_name": "Mesa", "verbose_name_plural": "Mesas"},
        ),
        migrations.CreateModel(
            name="BasketProduction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=0.0,
                        help_text="En  formato decimal: 0.5 equivale a 500Gr de producto",
                        verbose_name="Total pesado",
                    ),
                ),
                (
                    "turn",
                    models.SmallIntegerField(
                        choices=[(0, "Diurno"), (1, "Nocturno")], verbose_name="Categoría de la mesa"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="Costo por kilo"),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="Total generado"),
                ),
                (
                    "table",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="baskets",
                        to="peladoydescabezado.table",
                        verbose_name="Mesa",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="product_baskets",
                        to="peladoydescabezado.person",
                        verbose_name="Trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cesta",
                "verbose_name_plural": "Cestas",
            },
        ),
    ]
