# Generated by Django 4.2.6 on 2025-05-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0005_alter_table_options_basketproduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="archived_at",
            field=models.DateTimeField(default=None, null=True, verbose_name="Mesa archivada"),
        ),
    ]
