# Generated by Django 4.2.6 on 2025-05-20 22:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0006_table_archived_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableProxyModel",
            fields=[],
            options={
                "verbose_name": "Gestión de peso",
                "verbose_name_plural": "Gestion de pesaje",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("peladoydescabezado.table",),
        ),
    ]
