# Generated by Django 4.2.6 on 2025-06-02 23:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0007_tableproxymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("number", models.PositiveBigIntegerField(db_index=True, verbose_name="Número de la granja")),
                ("name", models.CharField(max_length=100, verbose_name="Nombre de la granja")),
            ],
            options={
                "verbose_name": "Granja",
                "verbose_name_plural": "Granjas",
            },
        ),
        migrations.AddField(
            model_name="basketproduction",
            name="weight_totalization_method",
            field=models.SmallIntegerField(
                choices=[(0, "Por Cesta"), (1, "Por Kilo")], default=0, verbose_name="Metodo de totalización"
            ),
        ),
        migrations.CreateModel(
            name="Pool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("number", models.PositiveBigIntegerField(db_index=True, verbose_name="Número de la piscina")),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pools", to="peladoydescabezado.farm"
                    ),
                ),
            ],
            options={
                "verbose_name": "Piscina",
                "verbose_name_plural": "Piscinas",
            },
        ),
        migrations.AddField(
            model_name="basketproduction",
            name="pool",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productions",
                to="peladoydescabezado.pool",
                verbose_name="Piscina",
            ),
        ),
    ]
