# Generated by Django 4.2.6 on 2025-06-03 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peladoydescabezado", "0008_farm_basketproduction_weight_totalization_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("description", models.CharField(max_length=10, verbose_name="Talla")),
            ],
            options={
                "verbose_name": "Talla",
                "verbose_name_plural": "Tallas",
            },
        ),
        migrations.AlterModelOptions(
            name="basketproduction",
            options={"verbose_name": "Producción", "verbose_name_plural": "Producción"},
        ),
        migrations.CreateModel(
            name="Control",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, verbose_name="Código")),
                ("date_upload", models.DateField(verbose_name="Fecha de gestión")),
                (
                    "total_weight_received",
                    models.DecimalField(decimal_places=2, max_digits=7, verbose_name="Kilos de camarón recibido"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="production_control_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="production_control_checked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="production_control_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="daily_control",
                        to="peladoydescabezado.farm",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="daily_control",
                        to="peladoydescabezado.pool",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="production",
                        to="peladoydescabezado.size",
                        verbose_name="Talla",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="basketproduction",
            name="control",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="production",
                to="peladoydescabezado.control",
            ),
        ),
    ]
