# Generated by Django 4.2.6 on 2025-06-04 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0009_size_alter_basketproduction_options_control_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="Nombre de la granja"),
        ),
        migrations.AlterField(
            model_name="farm",
            name="number",
            field=models.PositiveBigIntegerField(
                db_index=True, default=None, null=True, verbose_name="Número de la granja"
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pools",
                to="peladoydescabezado.farm",
                verbose_name="Granja",
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="number",
            field=models.PositiveBigIntegerField(
                db_index=True, default=None, null=True, verbose_name="Número de la piscina"
            ),
        ),
    ]
