# Generated by Django 4.2.6 on 2025-06-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0010_alter_farm_name_alter_farm_number_alter_pool_farm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="identity_pic",
            field=models.ImageField(
                default=None, null=True, upload_to="peladoydescabezado/", verbose_name="Foto de la cédula o pasaporte"
            ),
        ),
    ]
