# Generated by Django 4.2.6 on 2025-06-16 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0014_alter_carnetmodels_options_and_more"),
        ("peladoydescabezado", "0011_alter_person_identity_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="settings.department",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("settings.department",),
        ),
        migrations.AlterField(
            model_name="person",
            name="department",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peladoydescabezado.department",
                verbose_name="Departamento",
            ),
        ),
    ]
