# Generated by Django 4.2.6 on 2025-06-18 08:41

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0012_department_alter_person_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weightness",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("weight", models.CharField(max_length=60, verbose_name="Denominación")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name": "Departamento", "verbose_name_plural": "Departamentos"},
        ),
    ]
