# Generated by Django 4.2.6 on 2025-06-19 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0014_alter_weightness_options_remove_control_farm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controldetail",
            name="farm",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="daily_control",
                to="peladoydescabezado.farm",
            ),
        ),
        migrations.AlterField(
            model_name="controldetail",
            name="pool",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="daily_control",
                to="peladoydescabezado.pool",
            ),
        ),
        migrations.AlterField(
            model_name="controldetail",
            name="total_weight_received",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=7, null=True, verbose_name="Kilos de camarón recibido"
            ),
        ),
    ]
