# Generated by Django 4.2.6 on 2025-06-24 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peladoydescabezado", "0015_alter_controldetail_farm_alter_controldetail_pool_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketproduction",
            name="saved_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="production_saveds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
