# Generated by Django 4.2.6 on 2025-06-29 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0016_basketproduction_saved_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportProxyModel",
            fields=[],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("peladoydescabezado.table",),
        ),
    ]
