# Generated by Django 4.2.6 on 2025-07-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0017_reportproxymodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_actived",
            field=models.BooleanField(default=True, verbose_name="Personal activado"),
        ),
    ]
