# Generated by Django 4.2.6 on 2025-07-07 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0018_person_is_actived"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportproxymodel",
            options={
                "permissions": [
                    ("can_generate_prod_reports", "Puede generar reporte de producción"),
                    ("can_generate_assist_reports", "Puede generar reportes de asistencia"),
                ],
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
            },
        ),
        migrations.AlterModelOptions(
            name="weightness",
            options={"verbose_name": "Talla", "verbose_name_plural": "Tallas"},
        ),
    ]
