# Generated by Django 4.2.6 on 2025-09-11 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0020_alter_basketproduction_control_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="is_actived",
        ),
    ]
