# Generated by Django 4.2.6 on 2026-02-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0021_remove_person_is_actived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="identity",
            field=models.PositiveIntegerField(db_index=True, verbose_name="Cédula"),
        ),
    ]
