# Generated by Django 4.2.6 on 2026-02-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peladoydescabezado", "0022_alter_person_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="consecutive",
            field=models.PositiveIntegerField(default=1, verbose_name="Consecutivo"),
        ),
        migrations.AddField(
            model_name="person",
            name="consecutive_code",
            field=models.CharField(
                default=None,
                help_text="Código único para el consecutivo: Ej. PYD-001",
                max_length=10,
                null=True,
                verbose_name="Código del consecutivo",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="lastnames",
            field=models.CharField(max_length=150, verbose_name="Código consecutivo"),
        ),
        migrations.AlterField(
            model_name="person",
            name="names",
            field=models.CharField(max_length=150, verbose_name="Mesa"),
        ),
    ]
