# Generated by Django 4.2.6 on 2023-11-04 04:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0007_alter_employee_date_entry_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="Identity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Activo"), (1, "Caducado"), (2, "Desactivado")],
                        default=0,
                        verbose_name="Estado del carnet",
                    ),
                ),
                ("emited_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de emisión")),
                ("expire_at", models.DateTimeField(verbose_name="Fecha de expiración")),
                (
                    "expirable",
                    models.BooleanField(
                        default=True,
                        help_text="Si esta opción esta activada, el carne expirará en la fecha establecioda (1 años a partir de la fecha) por defecto está activada",
                        verbose_name="Caduca",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="identities",
                        to="employees.employee",
                        verbose_name="Carnet del trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carnet",
                "verbose_name_plural": "Carnets",
            },
        ),
    ]
