# Generated by Django 4.2.6 on 2023-10-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cedula",
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Cédula"),
        ),
        migrations.AddField(
            model_name="user",
            name="date_entry_job",
            field=models.DateField(default=None, null=True, verbose_name="Fecha de ingreso"),
        ),
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Foto"),
        ),
    ]
