# Generated by Django 4.2.6 on 2023-10-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Apellido"),
        ),
    ]
