# Generated by Django 4.2.6 on 2023-10-29 03:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="cedula",
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_entry_job",
        ),
        migrations.RemoveField(
            model_name="user",
            name="picture",
        ),
    ]
