# Generated by Django 4.2.6 on 2024-03-20 21:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0011_employee_deleted_at"),
        ("indentities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfDiningRoom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("check_name", models.CharField(verbose_name="Tipo de checkeos")),
                ("start_time", models.TimeField(verbose_name="Horario de inicio")),
                ("end_time", models.TimeField(verbose_name="Hora maxima de chequeo")),
                (
                    "date_start",
                    models.DateTimeField(default=None, null=True, verbose_name="Fecha desde que se aplica el horario"),
                ),
                (
                    "is_all_day",
                    models.BooleanField(
                        help_text="Si esta opción está activada, este tipo de chequeo podra ser usada todo el día por lo tanto anula las horas limites pero además, será solo aplicada el día indicado en el campo -fecha desde que se aplica el horario- ",
                        verbose_name="Valido para todo el dia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuracíon de turno",
                "verbose_name_plural": "Configuración de turnos de comedor",
            },
        ),
        migrations.CreateModel(
            name="DiningChecking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "conf_dining_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="checkings",
                        to="dining_room.confdiningroom",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="dining_room_checkings",
                        to="employees.employee",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="dining_room_checkings",
                        to="indentities.identity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
