# Generated by Django 4.2.6 on 2024-03-29 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("indentities", "0001_initial"),
        ("dining_room", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diningchecking",
            options={"verbose_name": "Chequeo de comedor", "verbose_name_plural": "Chequeos de comedor"},
        ),
        migrations.AlterField(
            model_name="diningchecking",
            name="identity",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="dining_room_checkings",
                to="indentities.identity",
            ),
        ),
    ]
