# Generated by Django 4.2.6 on 2024-03-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dining_room", "0002_alter_diningchecking_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="confdiningroom",
            name="is_active",
            field=models.DateTimeField(default=None, null=True, verbose_name="Turno desactivado"),
        ),
        migrations.AlterField(
            model_name="confdiningroom",
            name="check_name",
            field=models.CharField(verbose_name="Beneficio"),
        ),
    ]
