# Generated by Django 4.2.6 on 2024-03-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dining_room", "0003_confdiningroom_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confdiningroom",
            name="is_all_day",
            field=models.BooleanField(
                default=False,
                help_text="Si esta opción está activada, este tipo de chequeo podra ser usada todo el día por lo tanto anula las horas limites pero además, será solo aplicada el día indicado en el campo -fecha desde que se aplica el horario- ",
                verbose_name="Valido para todo el dia",
            ),
        ),
    ]
