# Generated by Django 4.2.6 on 2024-04-28 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0012_employee_is_removed"),
        ("dining_room", "0004_alter_confdiningroom_is_all_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diningchecking",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dining_room_checkings",
                to="employees.employee",
            ),
        ),
    ]
