# Generated by Django 4.2.6 on 2024-07-08 22:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dining_room", "0006_alter_diningchecking_conf_dining_room_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiningRoomProxyModel",
            fields=[],
            options={
                "verbose_name": "Gestión",
                "verbose_name_plural": "Gestión de comedor",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("dining_room.confdiningroom",),
        ),
        migrations.AlterModelOptions(
            name="confdiningroom",
            options={
                "permissions": [("can_see_management", "Gestiona comedor")],
                "verbose_name": "Configuracíon de turno",
                "verbose_name_plural": "Configuración de turnos de comedor",
            },
        ),
    ]
