# Generated by Django 4.2.6 on 2024-07-08 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dining_room", "0007_diningroomproxymodel_alter_confdiningroom_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="confdiningroom",
            options={
                "verbose_name": "Configuracíon de turno",
                "verbose_name_plural": "Configuración de turnos de comedor",
            },
        ),
    ]
