# Generated by Django 4.2.6 on 2024-07-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dining_room", "0009_confdiningroom_is_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="diningchecking",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
    ]
