# Generated by Django 4.2.6 on 2023-10-29 21:31

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("enabled", "Activo"), ("disabled", "Desactivado")],
                        default="enabled",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("client_ip", models.CharField(db_index=True, max_length=24, verbose_name="IP del cliente")),
                ("description", models.CharField(max_length=70, verbose_name="Título")),
                ("note", models.TextField(blank=True, default="", verbose_name="Observación")),
            ],
            options={
                "verbose_name": "Punto de entrada",
                "verbose_name_plural": "Puntos de entrada",
            },
        ),
    ]
