# Generated by Django 4.2.6 on 2024-05-21 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timetable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Hora de inicio del turno")),
                ("end_time", models.TimeField(verbose_name="Hora de salida del turno")),
                ("is_active", models.BooleanField(default=True, verbose_name="Configuracion activa")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="timetables",
                        to="settings.department",
                        verbose_name="Departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuraciones de horario",
                "verbose_name_plural": "Configuración horaria",
            },
        ),
    ]
