# Generated by Django 4.2.6 on 2024-08-25 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_timetable"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkCenter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=70, verbose_name="Nombre de la empresa")),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=10, verbose_name="Codigo de la empresa"
                    ),
                ),
                (
                    "main",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar opción si esta es la empresa principal del grupo",
                        verbose_name="Empreza matriz/principal",
                    ),
                ),
                ("address", models.TextField(blank=True, default="", verbose_name="Dirección fiscal o fisica")),
                ("is_active", models.BooleanField(default=True, verbose_name="Indicar si la empresa continua activa")),
                ("opened_at", models.DateField(default=None, null=True, verbose_name="Fecha de inicio")),
            ],
            options={
                "verbose_name": "Empresa/Centro de trabajo",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="work_center",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="settings.workcenter",
            ),
        ),
    ]
