# Generated by Django 4.2.6 on 2024-08-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_workcenter_department_work_center"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="work_center",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="settings.workcenter",
                verbose_name="Empresa",
            ),
        ),
    ]
