# Generated by Django 4.2.6 on 2024-09-07 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0005_alter_department_work_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientconfig",
            name="allow_fingerprint_clocking",
            field=models.BooleanField(default=False, verbose_name="Permitir chequeo por huella"),
        ),
        migrations.AddField(
            model_name="clientconfig",
            name="allow_qr_clocking",
            field=models.BooleanField(default=True, verbose_name="Permitir chequeo por QR"),
        ),
        migrations.AddField(
            model_name="clientconfig",
            name="woek_center",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="entrypoints",
                to="settings.workcenter",
            ),
        ),
    ]
