# Generated by Django 4.2.6 on 2024-09-07 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0006_clientconfig_allow_fingerprint_clocking_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientconfig",
            name="woek_center",
        ),
        migrations.AddField(
            model_name="clientconfig",
            name="work_center",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="entrypoints",
                to="settings.workcenter",
                verbose_name="Empresa",
            ),
        ),
    ]
