# Generated by Django 4.2.6 on 2024-09-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0009_workcenter_is_current_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="workcenter",
            name="allow_clocking_from_another_workcenter",
            field=models.BooleanField(default=False, verbose_name="Permitir chequeos de empleados de otra empresa"),
        ),
    ]
