# Generated by Django 4.2.6 on 2024-12-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0010_workcenter_allow_clocking_from_another_workcenter"),
    ]

    operations = [
        migrations.AddField(
            model_name="workcenter",
            name="rif",
            field=models.CharField(
                blank=True, default="", help_text="Ejemplo: J-1010101010", max_length=15, null=True
            ),
        ),
    ]
