# Generated by Django 4.2.6 on 2024-12-12 23:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0011_workcenter_rif"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarnetModels",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("modelo", models.CharField(max_length=120, verbose_name="Modelo de carnet")),
                ("front_path", models.ImageField(upload_to="carnet_models", verbose_name="Imagen frontal")),
                ("back_path", models.ImageField(upload_to="carnet_models", verbose_name="Imagen trasera")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="workcenter",
            name="carnet_model",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_centers",
                to="settings.carnetmodels",
            ),
        ),
    ]
