# Generated by Django 4.2.6 on 2023-10-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clocking", "0002_remove_dailychecks_user_dailychecks_employee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailycalendar",
            options={
                "ordering": ["-date_day"],
                "verbose_name": "Calendario del sistema",
                "verbose_name_plural": "Días del calendario",
            },
        ),
        migrations.AlterModelOptions(
            name="dailychecks",
            options={
                "ordering": ["-created"],
                "verbose_name": "Chequeo del día",
                "verbose_name_plural": "Chequeos diarios",
            },
        ),
        migrations.AddField(
            model_name="dailychecks",
            name="checking_type",
            field=models.IntegerField(
                choices=[(0, "Entrada"), (1, "Salida")], default=0, verbose_name="Tipo de checkeo"
            ),
        ),
    ]
