# Generated by Django 4.2.6 on 2023-10-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clocking", "0003_alter_dailycalendar_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailychecks",
            options={
                "ordering": ["-time"],
                "verbose_name": "Chequeo del día",
                "verbose_name_plural": "Chequeos diarios",
            },
        ),
        migrations.AddField(
            model_name="dailychecks",
            name="time",
            field=models.TimeField(auto_now_add=True, default=None, verbose_name="Hora de chequeo"),
            preserve_default=False,
        ),
    ]
