# Generated by Django 4.2.6 on 2023-10-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clocking", "0005_alter_dailychecks_checking_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailychecks",
            name="time",
            field=models.TimeField(auto_now_add=True, verbose_name="Hora de chequeo"),
        ),
    ]
