# Generated by Django 4.2.6 on 2023-10-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clocking", "0006_alter_dailychecks_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailychecks",
            name="checking_time",
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name="Fecha de checkeo"),
            preserve_default=False,
        ),
    ]
