# Generated by Django 4.2.6 on 2023-11-12 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clocking", "0007_dailychecks_checking_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailychecks",
            options={
                "ordering": ["-checking_time", "employee_id", "-id"],
                "verbose_name": "Chequeo del día",
                "verbose_name_plural": "Chequeos diarios",
            },
        ),
    ]
