# Generated by Django 4.2.6 on 2024-01-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clocking", "0010_alter_dailycalendarobservation_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycalendarobservation",
            name="check_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Entrada"), (2, "Salida"), (3, "Entrada y salida")],
                default=3,
                verbose_name="Tipo de observación",
            ),
        ),
    ]
