# Generated by Django 4.2.6 on 2024-01-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clocking", "0011_dailycalendarobservation_check_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailycalendarobservation",
            name="check_type",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Salida"), (3, "Entrada y salida")], default=3, verbose_name="Tipo de observación"
            ),
        ),
    ]
