# Generated by Django 4.2.6 on 2024-04-28 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0012_employee_is_removed"),
        ("clocking", "0012_alter_dailycalendarobservation_check_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailycalendarobservation",
            name="calendar_day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observations",
                to="clocking.dailycalendar",
                verbose_name="Día del calendario",
            ),
        ),
        migrations.AlterField(
            model_name="dailychecks",
            name="daily",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_user_checks",
                to="clocking.dailycalendar",
            ),
        ),
        migrations.AlterField(
            model_name="dailychecks",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_checks",
                to="employees.employee",
                verbose_name="Trabajador",
            ),
        ),
    ]
