# Generated by Django 4.2.6 on 2024-05-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clocking", "0014_alter_dailycalendar_date_day_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailychecks",
            options={
                "ordering": ["-daily__date_day", "-checking_time", "employee_id", "-id"],
                "verbose_name": "Chequeo del día",
                "verbose_name_plural": "Chequeos diarios",
            },
        ),
        migrations.AlterField(
            model_name="dailychecks",
            name="checking_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Fecha de chequeo"),
        ),
    ]
