# Generated by Django 4.2.6 on 2024-06-10 23:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clocking", "0015_alter_dailychecks_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailychecks",
            options={
                "ordering": ["-daily__date_day", "employee_id", "-id"],
                "verbose_name": "Chequeo del día",
                "verbose_name_plural": "Chequeos diarios",
            },
        ),
    ]
