# Generated by Django 4.2.6 on 2024-09-09 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0010_workcenter_allow_clocking_from_another_workcenter"),
        ("clocking", "0017_dailychecksproxymodeladmin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailychecks",
            name="entrypoint",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clockings",
                to="settings.clientconfig",
                verbose_name="Punto de entrada",
            ),
        ),
    ]
