# Generated by Django 4.2.6 on 2025-07-02 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0018_employee_is_actived"),
        ("peladoydescabezado", "0017_reportproxymodel"),
        ("clocking", "0018_dailychecks_entrypoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailychecks",
            name="person",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_checks",
                to="peladoydescabezado.person",
                verbose_name="Trabajador",
            ),
        ),
        migrations.AlterField(
            model_name="dailychecks",
            name="employee",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_checks",
                to="employees.employee",
                verbose_name="Trabajador",
            ),
        ),
    ]
