# Generated by Django 4.2.6 on 2025-07-02 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0018_employee_is_actived"),
        ("peladoydescabezado", "0018_person_is_actived"),
        ("clocking", "0019_dailychecks_person_alter_dailychecks_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycalendarobservation",
            name="person",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_observations",
                to="peladoydescabezado.person",
                verbose_name="Trabajador (Pelado y descabezado)",
            ),
        ),
        migrations.AlterField(
            model_name="dailycalendarobservation",
            name="employer",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_observations",
                to="employees.employee",
                verbose_name="Trabajador",
            ),
        ),
        migrations.AlterField(
            model_name="dailychecks",
            name="person",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_checks",
                to="peladoydescabezado.person",
                verbose_name="Trabajador (Pelado y descabezado)",
            ),
        ),
    ]
