# Generated by Django 4.2.6 on 2026-04-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clocking", "0020_dailycalendarobservation_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailychecks",
            name="deleted_at",
            field=models.DateTimeField(default=None, null=True, verbose_name="Eliminado"),
        ),
    ]
