# Generated by Django 4.2.6 on 2023-11-06 23:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0007_alter_employee_date_entry_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "total_hours",
                    models.PositiveBigIntegerField(default=0, verbose_name="Cantidad de horas realizadas"),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="employees.employee"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
