# Generated by Django 4.2.6 on 2023-11-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timereport",
            name="total_hours",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=17, verbose_name="Cantidad de horas realizadas"
            ),
        ),
    ]
