# Generated by Django 4.2.6 on 2026-03-02 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0003_timereport_end_at_timereport_start_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("report_name", models.CharField(max_length=200, verbose_name="Nombre del reporte")),
                (
                    "report_format",
                    models.SmallIntegerField(choices=[(0, "PDF"), (1, "Excel")], verbose_name="Formato"),
                ),
                ("parameters", models.JSONField(blank=True, default=dict, verbose_name="Parámetros")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="Dirección IP")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de reporte",
                "verbose_name_plural": "Logs de reportes",
                "ordering": ["-created"],
            },
        ),
    ]
